name: ArtaphyCore
version: '${version}'
main: org.artaphy.artaphyCore.ArtaphyCore
api-version: '1.21'
load: STARTUP
authors: [ Artaphy ]
commands:
  fly:
    description: Toggle flight mode for yourself or another player
    usage: /fly [player] [-on|-off]
    permission: artaphycore.command.fly
permissions:
  artaphycore.command.fly:
    description: Allows the user to use the fly command
    default: op
  artaphycore.command.fly.others:
    description: Allows the user to toggle flight for other players
    default: op